# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-f59xcVrUuvCL8lElAumfHRqNQh-YED

Phase 1 - Data pipeline
"""

"""
PharmaTrade-MM — Phase 1: Data Pipeline & Validation
=====================================================
Run this in Google Colab cell-by-cell.
"""

# ============================================================
# CELL 0: CONFIG — CHANGE THESE TWO LINES FOR COLAB
# ============================================================
ZIP_PATH = "/content/All data DL project.zip"       # wherever you upload the zip
DATA_DIR = "/content/pharma_data/"           # extraction target
OUT_DIR  = "/content/processed/"             # where outputs go
EXTRACT_ZIP = True
# If your data is already extracted, set EXTRACT_ZIP = False
# EXTRACT_ZIP = False  # <-- Set True in Colab if starting from zip

# ============================================================
# CELL 1: IMPORTS & EXTRACTION
# ============================================================
import os
import zipfile
import pandas as pd
import numpy as np
import json
import warnings
warnings.filterwarnings("ignore")

if EXTRACT_ZIP:
    os.makedirs(DATA_DIR, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH, 'r') as z:
        z.extractall(DATA_DIR)
    print(f"Extracted to {DATA_DIR}")
    # If zip creates a subfolder, adjust DATA_DIR:
    extracted = os.listdir(DATA_DIR)
    print(f"Contents after extraction: {extracted}")
    # Uncomment & adjust if zip nests files in a subfolder:
    DATA_DIR = os.path.join(DATA_DIR, extracted[0])
else:
    print(f"Using existing data in {DATA_DIR}")

print(f"\nFiles in DATA_DIR:\n{os.listdir(DATA_DIR)}")

# ============================================================
# CELL 2: DEFINE TICKERS & LOAD RAW DATA
# ============================================================
TICKERS = ["PFE", "JNJ", "MRK", "ABBV", "BMY", "AMGN", "GILD", "BIIB"]
TRAIN_END = "2021-12-31"
TEST_START = "2022-01-03"

# --- 2a: Price + Technicals (consolidated file) ---
price_df = pd.read_csv(os.path.join(DATA_DIR, "price_technicals.csv"), parse_dates=["date"])
price_df = price_df.sort_values(["ticker", "date"]).reset_index(drop=True)

print("=" * 60)
print("PRICE + TECHNICALS")
print("=" * 60)
print(f"Shape: {price_df.shape}")
print(f"Tickers: {sorted(price_df['ticker'].unique())}")
print(f"Date range: {price_df['date'].min().date()} to {price_df['date'].max().date()}")
print(f"Rows per ticker:\n{price_df['ticker'].value_counts().sort_index()}")
print(f"\nNull counts:\n{price_df.isnull().sum()}")
print(f"\nSample:\n{price_df.head(3)}")

# --- 2b: Sentiment Daily ---
sent_df = pd.read_csv(os.path.join(DATA_DIR, "sentiment_daily.csv"), parse_dates=["date"])
sent_df = sent_df.sort_values(["ticker", "date"]).reset_index(drop=True)

print("\n" + "=" * 60)
print("SENTIMENT DAILY")
print("=" * 60)
print(f"Shape: {sent_df.shape}")
print(f"Tickers: {sorted(sent_df['ticker'].unique())}")
print(f"Date range: {sent_df['date'].min().date()} to {sent_df['date'].max().date()}")
print(f"Rows per ticker:\n{sent_df['ticker'].value_counts().sort_index()}")
print(f"\nNull counts:\n{sent_df.isnull().sum()}")

# How many days actually have filings (n_filings > 0)?
filing_days = sent_df[sent_df["n_filings"] > 0]
print(f"\nDays with actual filings (n_filings > 0): {len(filing_days)} / {len(sent_df)}")
print(f"Filing days per ticker:\n{filing_days['ticker'].value_counts().sort_index()}")
print(f"\nSample (filing day):\n{filing_days.head(3)}")

# --- 2c: FDA Event Calendar ---
fda_cal = pd.read_csv(os.path.join(DATA_DIR, "fda_event_calendar.csv"), parse_dates=["date"])
fda_cal = fda_cal.sort_values(["ticker", "date"]).reset_index(drop=True)

print("\n" + "=" * 60)
print("FDA EVENT CALENDAR")
print("=" * 60)
print(f"Shape: {fda_cal.shape}")
print(f"Tickers: {sorted(fda_cal['ticker'].unique())}")
print(f"Date range: {fda_cal['date'].min().date()} to {fda_cal['date'].max().date()}")
print(f"\nEvent types:\n{fda_cal['event_type'].value_counts()}")
print(f"\nOutcomes:\n{fda_cal['outcome'].value_counts()}")
print(f"\nEvents per ticker:\n{fda_cal['ticker'].value_counts().sort_index()}")
print(f"\nFull calendar:\n{fda_cal[['date','ticker','event_type','drug_name','outcome','px_1d_ret_pct','px_5d_ret_pct']].to_string()}")

# --- 2d: FDA Timing Features ---
fda_timing = pd.read_csv(os.path.join(DATA_DIR, "fda_timing_features.csv"), parse_dates=["date", "as_of_date"])
fda_timing = fda_timing.sort_values(["ticker", "as_of_date", "date"]).reset_index(drop=True)

print("\n" + "=" * 60)
print("FDA TIMING FEATURES")
print("=" * 60)
print(f"Shape: {fda_timing.shape}")
print(f"Tickers: {sorted(fda_timing['ticker'].unique())}")
print(f"as_of_date range: {fda_timing['as_of_date'].min().date()} to {fda_timing['as_of_date'].max().date()}")
print(f"days_to_event range: {fda_timing['days_to_event'].min()} to {fda_timing['days_to_event'].max()}")
print(f"\nSample:\n{fda_timing[['as_of_date','ticker','event_type','drug_name','days_to_event','outcome','px_1d_ret_pct']].head(5)}")

# --- 2e: XPH Benchmark ---
xph_df = pd.read_csv(os.path.join(DATA_DIR, "xph_benchmark.csv"), parse_dates=["Date"])
xph_df = xph_df.rename(columns={"Date": "date", "Close": "close", "Volume": "volume",
                                  "High": "high", "Low": "low", "Open": "open"})
xph_df = xph_df.sort_values("date").reset_index(drop=True)

print("\n" + "=" * 60)
print("XPH BENCHMARK")
print("=" * 60)
print(f"Shape: {xph_df.shape}")
print(f"Date range: {xph_df['date'].min().date()} to {xph_df['date'].max().date()}")
print(f"Sample:\n{xph_df.head(3)}")

# ============================================================
# CELL 3: DATE ALIGNMENT CHECK
# ============================================================
print("\n" + "=" * 60)
print("DATE ALIGNMENT CHECK")
print("=" * 60)

# Get the set of trading dates per ticker from price data
date_sets = {}
for t in TICKERS:
    dates = set(price_df[price_df["ticker"] == t]["date"])
    date_sets[t] = dates

# Check all tickers have the same dates
ref_dates = date_sets[TICKERS[0]]
alignment_ok = True
for t in TICKERS[1:]:
    diff = ref_dates.symmetric_difference(date_sets[t])
    if diff:
        print(f"WARNING: {t} has {len(diff)} date mismatches vs {TICKERS[0]}")
        alignment_ok = False

if alignment_ok:
    print(f"All 8 tickers perfectly aligned: {len(ref_dates)} trading days each")

# Check sentiment covers same dates
sent_dates = {}
for t in TICKERS:
    sent_dates[t] = set(sent_df[sent_df["ticker"] == t]["date"])

for t in TICKERS:
    missing_in_sent = date_sets[t] - sent_dates[t]
    missing_in_price = sent_dates[t] - date_sets[t]
    if missing_in_sent or missing_in_price:
        print(f"{t}: {len(missing_in_sent)} price dates missing in sentiment, "
              f"{len(missing_in_price)} sentiment dates missing in price")

# Check FDA timing covers the date range
fda_as_of_dates = set(fda_timing["as_of_date"])
fda_coverage = fda_as_of_dates.intersection(ref_dates)
print(f"\nFDA timing features cover {len(fda_coverage)} / {len(ref_dates)} trading days")
print(f"FDA timing unique tickers with data: {sorted(fda_timing['ticker'].unique())}")

# ============================================================
# CELL 4: SENTIMENT ENHANCEMENT — FILING DECAY
# ============================================================
print("\n" + "=" * 60)
print("SENTIMENT ENHANCEMENT — FILING DECAY")
print("=" * 60)

# Strategy: On days with no filing (n_filings=0), the raw data shows zeros.
# We forward-fill the last real filing's sentiment with exponential decay (half-life = 5 days).
# This gives the agent a fading memory of recent filings rather than an abrupt zero.

DECAY_HALFLIFE = 5  # days

def apply_sentiment_decay(group):
    """For a single ticker's sentiment timeseries, forward-fill with exponential decay."""
    g = group.sort_values("date").copy()

    last_pos = 0.0
    last_neg = 0.0
    last_neu = 1.0
    last_net = 0.0
    days_since = 999

    decayed_rows = []
    for _, row in g.iterrows():
        if row["n_filings"] > 0:
            last_pos = row["sentiment_pos"]
            last_neg = row["sentiment_neg"]
            last_neu = row["sentiment_neu"]
            last_net = row["net_sentiment"]
            days_since = 0
            decayed_rows.append(row)
        else:
            days_since += 1
            decay = np.exp(-np.log(2) * days_since / DECAY_HALFLIFE)
            new_row = row.copy()
            new_row["sentiment_pos"] = last_pos * decay
            new_row["sentiment_neg"] = last_neg * decay
            new_row["sentiment_neu"] = 1.0 - (last_pos * decay + last_neg * decay)
            new_row["net_sentiment"] = last_net * decay
            decayed_rows.append(new_row)

    return pd.DataFrame(decayed_rows)

sent_enhanced = sent_df.groupby("ticker", group_keys=False).apply(apply_sentiment_decay)
sent_enhanced = sent_enhanced.reset_index(drop=True)

before_nonzero = (sent_df["net_sentiment"] != 0).sum()
after_nonzero = (sent_enhanced["net_sentiment"] != 0).sum()
print(f"Non-zero net_sentiment days — Before decay: {before_nonzero}, After decay: {after_nonzero}")
print(f"Sentiment signal coverage: {before_nonzero/len(sent_df)*100:.1f}% -> {after_nonzero/len(sent_enhanced)*100:.1f}%")

# Sample: show a ticker around a filing date
sample_ticker = "PFE"
sample_filing_dates = sent_enhanced[(sent_enhanced["ticker"] == sample_ticker) & (sent_enhanced["n_filings"] > 0)]["date"].iloc[:2]
if len(sample_filing_dates) > 0:
    d = sample_filing_dates.iloc[0]
    window = sent_enhanced[(sent_enhanced["ticker"] == sample_ticker) &
                           (sent_enhanced["date"] >= d - pd.Timedelta(days=2)) &
                           (sent_enhanced["date"] <= d + pd.Timedelta(days=10))]
    print(f"\nDecay example — {sample_ticker} around filing date {d.date()}:")
    print(window[["date", "ticker", "net_sentiment", "n_filings"]].to_string(index=False))

# ============================================================
# CELL 5: BUILD FDA FEATURE VECTORS PER TRADING DAY
# ============================================================
print("\n" + "=" * 60)
print("FDA FEATURE ENGINEERING")
print("=" * 60)

print(f"Event types: {fda_cal['event_type'].unique().tolist()}")
print(f"Therapeutic areas: {fda_cal['therapeutic_area'].unique().tolist()}")
print(f"Outcomes: {fda_cal['outcome'].unique().tolist()}")

# For each as_of_date + ticker, pick the NEAREST upcoming event
fda_nearest = fda_timing.loc[fda_timing.groupby(["ticker", "as_of_date"])["days_to_event"].idxmin()]
fda_nearest = fda_nearest.rename(columns={"as_of_date": "date_key"})

print(f"\nNearest-event records: {len(fda_nearest)}")
print(f"Sample:\n{fda_nearest[['date_key','ticker','event_type','drug_name','days_to_event','outcome']].head(10).to_string()}")

# Build one-hot encodings
event_types = sorted(fda_cal["event_type"].unique())
therapy_areas = sorted(fda_cal["therapeutic_area"].unique())
print(f"\nOne-hot event types ({len(event_types)}): {event_types}")
print(f"One-hot therapy areas ({len(therapy_areas)}): {therapy_areas}")

# Historical average reactions — ONLY from training period (no lookahead)
fda_cal_train = fda_cal[fda_cal["date"] <= TRAIN_END]
hist_reactions = fda_cal_train.groupby(["ticker", "event_type"]).agg(
    hist_1d_ret=("px_1d_ret_pct", "mean"),
    hist_5d_ret=("px_5d_ret_pct", "mean")
).reset_index()
print(f"\nHistorical reaction stats (train only):\n{hist_reactions.to_string()}")

# ============================================================
# CELL 6: MERGE EVERYTHING INTO A UNIFIED DATASET
# ============================================================
print("\n" + "=" * 60)
print("BUILDING UNIFIED DATASET")
print("=" * 60)

# Start with price as the spine
unified = price_df.copy()

# Merge enhanced sentiment
sent_merge = sent_enhanced[["date", "ticker", "sentiment_pos", "sentiment_neg",
                             "sentiment_neu", "net_sentiment", "n_filings"]].copy()
sent_merge.columns = ["date", "ticker", "sent_pos", "sent_neg", "sent_neu", "sent_net", "n_filings"]

unified = unified.merge(sent_merge, on=["date", "ticker"], how="left")

# Prepare FDA features for merge
fda_merge = fda_nearest[["date_key", "ticker", "event_type", "therapeutic_area",
                          "days_to_event", "outcome"]].copy()
fda_merge = fda_merge.rename(columns={"date_key": "date"})

# Add historical reactions
fda_merge = fda_merge.merge(hist_reactions, on=["ticker", "event_type"], how="left")
fda_merge["hist_1d_ret"] = fda_merge["hist_1d_ret"].fillna(0)
fda_merge["hist_5d_ret"] = fda_merge["hist_5d_ret"].fillna(0)

# One-hot encode event_type and therapeutic_area
for et in event_types:
    fda_merge[f"evt_{et}"] = (fda_merge["event_type"] == et).astype(int)
for ta in therapy_areas:
    safe_name = ta.replace(" ", "_").replace("/", "_")
    fda_merge[f"ta_{safe_name}"] = (fda_merge["therapeutic_area"] == ta).astype(int)

# is_event_window: within 5 trading days
fda_merge["is_event_window"] = (fda_merge["days_to_event"] <= 5).astype(int)

# Drop raw categorical columns before merge
fda_feature_cols = [c for c in fda_merge.columns if c not in ["event_type", "therapeutic_area", "outcome"]]
fda_merge = fda_merge[fda_feature_cols]

unified = unified.merge(fda_merge, on=["date", "ticker"], how="left")

# Fill NaN for days with no upcoming FDA event
unified["days_to_event"] = unified["days_to_event"].fillna(999).astype(int)
unified["is_event_window"] = unified["is_event_window"].fillna(0).astype(int)
unified["hist_1d_ret"] = unified["hist_1d_ret"].fillna(0)
unified["hist_5d_ret"] = unified["hist_5d_ret"].fillna(0)

# Fill one-hot FDA columns with 0
evt_cols = [c for c in unified.columns if c.startswith("evt_") or c.startswith("ta_")]
unified[evt_cols] = unified[evt_cols].fillna(0).astype(int)

# Fill any remaining sentiment NaN
sent_cols = ["sent_pos", "sent_neg", "sent_neu", "sent_net", "n_filings"]
for c in sent_cols:
    if c in unified.columns:
        unified[c] = unified[c].fillna(0)

# ============================================================
# CELL 7: TRAIN / TEST SPLIT & FINAL VALIDATION
# ============================================================
train = unified[unified["date"] <= TRAIN_END].copy()
test = unified[unified["date"] >= TEST_START].copy()

print(f"Unified dataset shape: {unified.shape}")
print(f"Columns ({len(unified.columns)}): {unified.columns.tolist()}")
print(f"\nTrain: {train.shape} — {train['date'].min().date()} to {train['date'].max().date()}")
print(f"Test:  {test.shape}  — {test['date'].min().date()} to {test['date'].max().date()}")
print(f"\nTrain rows per ticker:\n{train['ticker'].value_counts().sort_index()}")
print(f"\nTest rows per ticker:\n{test['ticker'].value_counts().sort_index()}")

# Final null check
null_check = unified.isnull().sum()
nulls = null_check[null_check > 0]
if len(nulls) == 0:
    print("\n✅ No nulls in unified dataset!")
else:
    print(f"\n⚠️ Remaining nulls:\n{nulls}")

# Feature group summary
price_features = ["open", "high", "low", "close", "volume", "rsi", "macd", "macd_signal",
                   "macd_diff", "bb_upper", "bb_middle", "bb_lower", "bb_pct", "bb_width",
                   "log_return", "volume_sma20", "volume_ratio"]
sent_features = ["sent_pos", "sent_neg", "sent_neu", "sent_net", "n_filings"]
fda_features = ["days_to_event", "is_event_window", "hist_1d_ret", "hist_5d_ret"] + evt_cols

print(f"\n{'='*60}")
print(f"FEATURE SUMMARY")
print(f"{'='*60}")
print(f"Price + Technical features ({len(price_features)}): {price_features}")
print(f"Sentiment features ({len(sent_features)}): {sent_features}")
print(f"FDA features ({len(fda_features)}): {fda_features}")
print(f"Total features for model: {len(price_features) + len(sent_features) + len(fda_features)}")

# ============================================================
# CELL 8: SAVE PROCESSED DATA
# ============================================================
os.makedirs(OUT_DIR, exist_ok=True)

unified.to_csv(os.path.join(OUT_DIR, "unified_dataset.csv"), index=False)
train.to_csv(os.path.join(OUT_DIR, "train_dataset.csv"), index=False)
test.to_csv(os.path.join(OUT_DIR, "test_dataset.csv"), index=False)
xph_df.to_csv(os.path.join(OUT_DIR, "xph_processed.csv"), index=False)

# Save feature group names for downstream modules
feature_config = {
    "tickers": TICKERS,
    "train_end": TRAIN_END,
    "test_start": TEST_START,
    "price_features": price_features,
    "sentiment_features": sent_features,
    "fda_features": fda_features,
    "event_types": event_types,
    "therapy_areas": therapy_areas,
    "decay_halflife": DECAY_HALFLIFE
}
with open(os.path.join(OUT_DIR, "feature_config.json"), "w") as f:
    json.dump(feature_config, f, indent=2)

print(f"\n✅ Saved to {OUT_DIR}:")
print(f"   - unified_dataset.csv ({unified.shape})")
print(f"   - train_dataset.csv ({train.shape})")
print(f"   - test_dataset.csv ({test.shape})")
print(f"   - xph_processed.csv ({xph_df.shape})")
print(f"   - feature_config.json")

# ============================================================
# CELL 9: QUICK SANITY STATS — PASTE THIS OUTPUT BACK TO ME
# ============================================================
print("\n" + "=" * 60)
print("PASTE THIS ENTIRE OUTPUT BACK TO ME")
print("=" * 60)
print(f"unified shape: {unified.shape}")
print(f"train shape: {train.shape}")
print(f"test shape: {test.shape}")
print(f"columns: {unified.columns.tolist()}")
print(f"dtypes:\n{unified.dtypes}")
print(f"\ntrain date range: {train['date'].min()} to {train['date'].max()}")
print(f"test date range: {test['date'].min()} to {test['date'].max()}")
print(f"\nFDA event window days in train: {train['is_event_window'].sum()}")
print(f"FDA event window days in test: {test['is_event_window'].sum()}")
print(f"\nSentiment non-zero days in train: {(train['sent_net'] != 0).sum()} / {len(train)}")
print(f"Sentiment non-zero days in test: {(test['sent_net'] != 0).sum()} / {len(test)}")
print(f"\nPrice log_return stats:\n{unified['log_return'].describe()}")
print(f"\nDays to event distribution:\n{unified['days_to_event'].value_counts().head(10)}")
print(f"\nnull total: {unified.isnull().sum().sum()}")

train_df = pd.read_csv("processed/train_dataset.csv")
test_df = pd.read_csv("processed/test_dataset.csv")

train.info()

